cmd/aaq-server/aaq-server.go
manifests/examples/carq-example.yaml
pkg/aaq-controller/aaq-gate-controller/aaq-gate-controller.go
pkg/aaq-controller/additional-openshift-controllers/carq-controller/carq-controller.go
pkg/aaq-controller/additional-openshift-controllers/crq-controller/crq-controller.go
pkg/aaq-controller/application.go
pkg/aaq-controller/arq-controller/arq-controller.go
pkg/aaq-controller/configuration-controller/configuration-controller.go
pkg/aaq-controller/rq-controller/rq-controller.go
pkg/aaq-operator/cr-manager.go
pkg/aaq-operator/operator_test.go
pkg/aaq-operator/resources/cluster/aaqserver.go
pkg/aaq-operator/resources/cluster/factory.go
pkg/aaq-operator/resources/crds_generated.go
pkg/aaq-operator/resources/namespaced/aaqserver.go
pkg/aaq-operator/resources/namespaced/controller.go
pkg/aaq-operator/resources/namespaced/factory.go
pkg/aaq-server/aaq-handler.go
pkg/aaq-server/aaq-server.go
pkg/aaq-server/aaq-server_test.go
pkg/aaq-server/handler/handler.go
pkg/util/util.go
staging/src/kubevirt.io/applications-aware-quota-api/pkg/apis/core/v1alpha1/types.go

Include cluster quota for pods even if we are
not in OCP there is no reason other clusters
can't use namespace wide quota for pods.
Cluster quota will be enabled by adding a feature gate as 
it may impact preformance
Fixes #
```release-note
NONE
```

Feature gate for cluster quota

---

pkg/aaq-operator/callbacks.go
pkg/aaq-operator/controller.go
pkg/aaq-operator/reconciler-hooks.go
pkg/aaq-operator/scc.go

Fixes #
```release-note
NONE
```

Add scc when on Openshift cluster

---

pkg/aaq-controller/application.go

For quota/namespaces Creations/Updates
Fixes #
```release-note
NONE
```

Add listener so we would respond faster

---

hack/build/bazel-build-builder.sh
hack/build/config.sh

Fixes #
```release-note
NONE
```

Update builder to the offical builder

---

hack/build/bazel-build-builder.sh
hack/build/config.sh

Fixes #
```release-note
NONE
```

Update the builder image

---

hack/build/bazel-build-builder.sh
hack/build/config.sh

Fixes #
```release-note
NONE
```

Update builder image on 1.1

---

OWNERS_ALIASES

Add myself as a reviewer of this repository.
```release-note
NONE
```

Add myself as a reviewer

---

hack/build/config.sh

Fixes #
```release-note
NONE
```

Update builder image to include make gen-proto dependencies

---

hack/build/build-functest.sh

Fixes #
```release-note
NONE
```

Move ginkgo binary to tests output dir

---

tests/aaq_operator_test.go
tests/aaq_server_test.go
tests/e2e_application_aware_cluster_resource_quota.go
tests/e2e_application_aware_resource_quota_test.go
tests/e2e_mirrors_quotas_test.go
tests/e2e_plugable_policies_test.go
tests/framework/framework.go
tests/tests_suite_test.go
tests/utils/aaq-utils.go

Fixes #
```release-note
NONE
```

[Tests] Modifications to Support Wider Environments

---

tests/aaq_operator_test.go
tests/aaq_server_test.go
tests/e2e_application_aware_cluster_resource_quota.go
tests/e2e_application_aware_resource_quota_test.go
tests/e2e_mirrors_quotas_test.go
tests/framework/framework.go
tests/tests_suite_test.go
tests/utils/aaq-utils.go

This is a manual cherry-pick of https://github.com/kubevirt/application-aware-quota/pull/85
it is needed to be manually because e2e test for plugable policies doesn't exist in this branch
Fixes #
```release-note
NONE
```

[release-v1.1] [Tests] Modifications to Support Wider Environments

---

README.md

Fixes #
```release-note
NONE
```

Add documentation on how to use the AAQ operator

---

tests/framework/framework.go

Fixes #
```release-note
NONE
```

Dump deployments and AAQ objects after failures for better debugging

---

hack/build/docker/builder/Dockerfile

prepare it for linter and to use the vendor vesion of ginkgo instead of hardcoded vesion.
Fixes #
```release-note
NONE
```

Refactor builder dockerFile

---

hack/build/docker/builder/Dockerfile

The \ in the end of the Run cmd is leftover
Fixes #
```release-note
NONE
```

Fix builder

---

hack/build/bootstrap-ginkgo.sh
hack/build/build-functest.sh
hack/build/config.sh
hack/build/run-functional-tests.sh
hack/build/run-unit-tests.sh

Use ginkgo by compiling it through vendor
To make sure that cli version match the tests versions
Use ginkgo directly instead of using the tests binary
Fixes #
```release-note
NONE
```

Match ginkgo version of the builder to vendor

---

go.mod
go.sum
vendor/github.com/golang/glog/glog.go
vendor/github.com/golang/glog/glog_file.go
vendor/github.com/golang/glog/glog_file_nonwindows.go
vendor/github.com/golang/glog/glog_file_windows.go
vendor/modules.txt

fix https://osv.dev/vulnerability/GO-2025-3372
Fixes #
```release-note
NONE
```

Bump github.com/golang/glog to v1.2.4

---

hack/build/docker/builder/Dockerfile

Update builder go version to match binaries versions
Fixes #
```release-note
NONE
```

Update builder go version

---

hack/build/docker/builder/Dockerfile

Update builder go version to match binaries versions
Fixes #
```release-note
NONE
```

[Release-v1.3]Update builder go version

---

pkg/aaq-controller/built-in-usage-calculators/virt-launcher-usage-calc.go
pkg/aaq-controller/built-in-usage-calculators/virt-launcher-usage-calc_test.go

Before this change, we used to check GuestCurrent during memory hotplug.
This caused a problem because after migration finished, but before the hotplug happened, GuestCurrent still held the old memory value.
This led to incorrect memory couting for the new
launcher, which should have used the new memory value since it already allocated memory for the hotplug.
Now, we use GuestRequested instead:
1. Before migration starts, we count the old value for the source and 0 for the target.
2. During migration, we count the old value for the source and the difference (Spec.Domain.Memory - GuestRequested) for the target.
3. After migration but before hotplug, we count the new value for the target.
4. After hotplug, the counting remains the same as step 3. …

Fix issue with memory hotplug counting during migration

---

hack/release.sh

the gpg and token files
Fixes #
```release-note
NONE
```

Don't require special perm for reading

---

hack/build/docker/builder/Dockerfile

Fixes #
```release-note
NONE
```

Update golang to version 1.23.6 for aaq builder

---

hack/build/config.sh

Fixes #
```release-note
NONE
```

Update builder to last image

---

hack/build/config.sh

https://github.com/kubevirt/application-aware-quota/pull/121
Fixes #
```release-note
NONE
```

Update builder with changes of PR#121

---

pkg/aaq-operator/resources/crds_generated.go
staging/src/kubevirt.io/application-aware-quota-api/pkg/apis/core/v1alpha1/types.go

Reverts kubevirt/application-aware-quota#139

Revert "types: add ARQ additional printer columns to reflect native RQ behavior"
